name: Auto-assign issues
on:
  issues:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue
        uses: peter-evans/assign-issue@v2
        with:
          assignees: tianshub, wang2yn84, lc5211, hgao327, sizhit2, abheesht17, jiangyangmu
